name: CI - Node.js

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'yarn'

    - run: npm pkg delete scripts.prepare

    - name: Install dependencies
      uses: yarn install --frozen-lockfile

    - name: Linting
      uses: yarn ci:lint

    - name: Typechecking
      uses: yarn typecheck

    - name: Testing
      uses: yarn test:ci
